#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SkillStore.Resource", IsApplication=true)]

namespace SkillStore
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int HelpPopUpFloatingAnimation = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int ShakeAnimation = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int TenTimes_CycleInterpolator = 2130968578;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080000
			public const int HistoryItemContextMenu = 2131230720;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060001
			public const int gray = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int gray_dark = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int gray_light = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int gray_overlay_shadow = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int green = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int green_dark = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int red = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int red_dark = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int yellow = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int yellow_dark = 2131099657;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int dummy_preview_picture = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int HandHoldingEgg_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int HandHoldingEgg_side_right_003 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int HandHoldingEgg_side_right_transparent = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int HelpPopUpBackground = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int HoldingEggLeft = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int HoldingSmartphone = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_action_about = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_action_accept = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_action_camera = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_action_help = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_action_next_item = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_action_overflow = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_action_previous_item = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_action_settings = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Icon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int preview_sample = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int PreviewSample = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int progress_seekbar_green = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int progress_seekbar_red = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int progress_seekbar_yellow = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int RoundBackground = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int RoundButtonBackground = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int RoundCornerButtonBackground = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Splash = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int thumb_green = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int thumb_red = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int thumb_yellow = 2130837532;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b0037
			public const int ActionAbout = 2131427383;
			
			// aapt resource value: 0x7f0b0038
			public const int ActionHelp = 2131427384;
			
			// aapt resource value: 0x7f0b0035
			public const int ActionMenu = 2131427381;
			
			// aapt resource value: 0x7f0b0036
			public const int ActionSettings = 2131427382;
			
			// aapt resource value: 0x7f0b0003
			public const int AnimationView = 2131427331;
			
			// aapt resource value: 0x7f0b002e
			public const int ArrowDown = 2131427374;
			
			// aapt resource value: 0x7f0b002c
			public const int ArrowUp = 2131427372;
			
			// aapt resource value: 0x7f0b002a
			public const int BackButton = 2131427370;
			
			// aapt resource value: 0x7f0b0024
			public const int ButtonBar = 2131427364;
			
			// aapt resource value: 0x7f0b0010
			public const int CancelButton = 2131427344;
			
			// aapt resource value: 0x7f0b001a
			public const int ClassHelp = 2131427354;
			
			// aapt resource value: 0x7f0b0018
			public const int ClassRow = 2131427352;
			
			// aapt resource value: 0x7f0b0019
			public const int ClassTextView = 2131427353;
			
			// aapt resource value: 0x7f0b0005
			public const int CountdownText = 2131427333;
			
			// aapt resource value: 0x7f0b0030
			public const int Date = 2131427376;
			
			// aapt resource value: 0x7f0b0009
			public const int DontShowAgainBox = 2131427337;
			
			// aapt resource value: 0x7f0b0011
			public const int FeedbackButton = 2131427345;
			
			// aapt resource value: 0x7f0b0016
			public const int FeedbackForm = 2131427350;
			
			// aapt resource value: 0x7f0b002b
			public const int FinishButton = 2131427371;
			
			// aapt resource value: 0x7f0b0017
			public const int FormTitle = 2131427351;
			
			// aapt resource value: 0x7f0b0029
			public const int ForwardsButton = 2131427369;
			
			// aapt resource value: 0x7f0b0027
			public const int LoadingRotator = 2131427367;
			
			// aapt resource value: 0x7f0b0001
			public const int ManualText1 = 2131427329;
			
			// aapt resource value: 0x7f0b000a
			public const int ManualText2 = 2131427338;
			
			// aapt resource value: 0x7f0b002d
			public const int Message = 2131427373;
			
			// aapt resource value: 0x7f0b0020
			public const int NotesHelp = 2131427360;
			
			// aapt resource value: 0x7f0b001e
			public const int NotesRow = 2131427358;
			
			// aapt resource value: 0x7f0b001f
			public const int NotesTextView = 2131427359;
			
			// aapt resource value: 0x7f0b0026
			public const int Overlay = 2131427366;
			
			// aapt resource value: 0x7f0b0034
			public const int OverlayStatusText = 2131427380;
			
			// aapt resource value: 0x7f0b0023
			public const int PictureHelp = 2131427363;
			
			// aapt resource value: 0x7f0b0022
			public const int PicturePreviewView = 2131427362;
			
			// aapt resource value: 0x7f0b0021
			public const int PictureRow = 2131427361;
			
			// aapt resource value: 0x7f0b002f
			public const int Preview = 2131427375;
			
			// aapt resource value: 0x7f0b0008
			public const int Result = 2131427336;
			
			// aapt resource value: 0x7f0b000f
			public const int ResultButtonBar = 2131427343;
			
			// aapt resource value: 0x7f0b0007
			public const int ResultText = 2131427335;
			
			// aapt resource value: 0x7f0b0002
			public const int ResultsAndAnimationBlock = 2131427330;
			
			// aapt resource value: 0x7f0b0006
			public const int ResultsView = 2131427334;
			
			// aapt resource value: 0x7f0b0013
			public const int SeekBar = 2131427347;
			
			// aapt resource value: 0x7f0b0012
			public const int SeekBarWrapper = 2131427346;
			
			// aapt resource value: 0x7f0b0025
			public const int SendButton = 2131427365;
			
			// aapt resource value: 0x7f0b0032
			public const int SettingsContent = 2131427378;
			
			// aapt resource value: 0x7f0b0004
			public const int SmartphoneImage = 2131427332;
			
			// aapt resource value: 0x7f0b0014
			public const int StartButton = 2131427348;
			
			// aapt resource value: 0x7f0b000d
			public const int StatusAndButtonBar = 2131427341;
			
			// aapt resource value: 0x7f0b000b
			public const int StatusAndButtonBlock = 2131427339;
			
			// aapt resource value: 0x7f0b000c
			public const int StatusAndProgressBar = 2131427340;
			
			// aapt resource value: 0x7f0b000e
			public const int StatusText = 2131427342;
			
			// aapt resource value: 0x7f0b0033
			public const int TabContentLayout = 2131427379;
			
			// aapt resource value: 0x7f0b0031
			public const int Tags = 2131427377;
			
			// aapt resource value: 0x7f0b001d
			public const int TagsHelp = 2131427357;
			
			// aapt resource value: 0x7f0b001b
			public const int TagsRow = 2131427355;
			
			// aapt resource value: 0x7f0b001c
			public const int TagsTextView = 2131427356;
			
			// aapt resource value: 0x7f0b0000
			public const int VersionText = 2131427328;
			
			// aapt resource value: 0x7f0b0028
			public const int ViewPager = 2131427368;
			
			// aapt resource value: 0x7f0b0015
			public const int title = 2131427349;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutActivityLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AnalyzerTabFragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EmptyHistoryItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int FeedbackActivityLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int HelpActivityLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int HelpPopUpLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int HistoryItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int HistoryTabFragment = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ReadFailedHistoryItem = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int SettingsActivityLayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int SplashActivityLayout = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int TabbedLayout = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int tabbed_activity_actions = 2131361792;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f07002b
			public const int AboutTitle = 2131165227;
			
			// aapt resource value: 0x7f070008
			public const int ActionAbout = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int ActionHelp = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int ActionMenu = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int ActionSettings = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int AddInfoServerAddress = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int AnalysisServerAddress = 2131165186;
			
			// aapt resource value: 0x7f070010
			public const int AnalysisSuccessful = 2131165200;
			
			// aapt resource value: 0x7f07000a
			public const int AnalyzerTitle = 2131165194;
			
			// aapt resource value: 0x7f070000
			public const int ApplicationName = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int ApplicationNameDebuggable = 2131165185;
			
			// aapt resource value: 0x7f070052
			public const int AudioRecorderStopped = 2131165266;
			
			// aapt resource value: 0x7f07002d
			public const int Author = 2131165229;
			
			// aapt resource value: 0x7f07002c
			public const int AuthorHeading = 2131165228;
			
			// aapt resource value: 0x7f070024
			public const int CancelButtonText = 2131165220;
			
			// aapt resource value: 0x7f070053
			public const int CheckFailed = 2131165267;
			
			// aapt resource value: 0x7f07003a
			public const int CheckFailedTip = 2131165242;
			
			// aapt resource value: 0x7f070046
			public const int CheckFailedTitle = 2131165254;
			
			// aapt resource value: 0x7f070054
			public const int CheckSuccessful = 2131165268;
			
			// aapt resource value: 0x7f070055
			public const int CheckingSamples = 2131165269;
			
			// aapt resource value: 0x7f070020
			public const int ClassDefaultText = 2131165216;
			
			// aapt resource value: 0x7f070026
			public const int ClassHelpText = 2131165222;
			
			// aapt resource value: 0x7f070067
			public const int DataFound = 2131165287;
			
			// aapt resource value: 0x7f070068
			public const int DataNotFound = 2131165288;
			
			// aapt resource value: 0x7f070038
			public const int DataNotFoundTip = 2131165240;
			
			// aapt resource value: 0x7f070044
			public const int DataNotFoundTitle = 2131165252;
			
			// aapt resource value: 0x7f070004
			public const int DateCulture = 2131165188;
			
			// aapt resource value: 0x7f07006a
			public const int DeleteFailed = 2131165290;
			
			// aapt resource value: 0x7f07003b
			public const int DeleteFailedTip = 2131165243;
			
			// aapt resource value: 0x7f070047
			public const int DeleteFailedTitle = 2131165255;
			
			// aapt resource value: 0x7f07006b
			public const int DeleteSuccessful = 2131165291;
			
			// aapt resource value: 0x7f070030
			public const int Description = 2131165232;
			
			// aapt resource value: 0x7f07002f
			public const int DescriptionHeading = 2131165231;
			
			// aapt resource value: 0x7f070013
			public const int EmptyListItem = 2131165203;
			
			// aapt resource value: 0x7f07000e
			public const int FeedbackButtonText = 2131165198;
			
			// aapt resource value: 0x7f07001e
			public const int FeedbackFormTitle = 2131165214;
			
			// aapt resource value: 0x7f07001d
			public const int FeedbackTitle = 2131165213;
			
			// aapt resource value: 0x7f07004c
			public const int FinishedPreparingAudioRecorderService = 2131165260;
			
			// aapt resource value: 0x7f070017
			public const int HelpTitle = 2131165207;
			
			// aapt resource value: 0x7f070011
			public const int HistoryTitle = 2131165201;
			
			// aapt resource value: 0x7f07000d
			public const int LaterButtonText = 2131165197;
			
			// aapt resource value: 0x7f070012
			public const int LoadingHistoryEntries = 2131165202;
			
			// aapt resource value: 0x7f07001c
			public const int ManualIndicatorText = 2131165212;
			
			// aapt resource value: 0x7f070058
			public const int NetworkConnected = 2131165272;
			
			// aapt resource value: 0x7f070069
			public const int NoDataStored = 2131165289;
			
			// aapt resource value: 0x7f070059
			public const int NoNetworkConnection = 2131165273;
			
			// aapt resource value: 0x7f070032
			public const int NoNetworkConnectionTip = 2131165234;
			
			// aapt resource value: 0x7f07003e
			public const int NoNetworkConnectionTitle = 2131165246;
			
			// aapt resource value: 0x7f07005c
			public const int NoServerConnection = 2131165276;
			
			// aapt resource value: 0x7f070033
			public const int NoServerConnectionTip = 2131165235;
			
			// aapt resource value: 0x7f07003f
			public const int NoServerConnectionTitle = 2131165247;
			
			// aapt resource value: 0x7f070022
			public const int NotesDefaultText = 2131165218;
			
			// aapt resource value: 0x7f070028
			public const int NotesHelpText = 2131165224;
			
			// aapt resource value: 0x7f070023
			public const int OkButtonText = 2131165219;
			
			// aapt resource value: 0x7f070005
			public const int PathOnDevice = 2131165189;
			
			// aapt resource value: 0x7f070029
			public const int PictureHelpText = 2131165225;
			
			// aapt resource value: 0x7f07002a
			public const int PictureLoadFailed = 2131165226;
			
			// aapt resource value: 0x7f070039
			public const int PictureLoadFailedTip = 2131165241;
			
			// aapt resource value: 0x7f070045
			public const int PictureLoadFailedTitle = 2131165253;
			
			// aapt resource value: 0x7f07004a
			public const int PreparingAudioRecorderService = 2131165258;
			
			// aapt resource value: 0x7f070062
			public const int ReadFailed = 2131165282;
			
			// aapt resource value: 0x7f070014
			public const int ReadFailedListItem = 2131165204;
			
			// aapt resource value: 0x7f070037
			public const int ReadFailedTip = 2131165239;
			
			// aapt resource value: 0x7f070043
			public const int ReadFailedTitle = 2131165251;
			
			// aapt resource value: 0x7f070063
			public const int ReadSuccessful = 2131165283;
			
			// aapt resource value: 0x7f070056
			public const int RecorderInitializationError = 2131165270;
			
			// aapt resource value: 0x7f07003c
			public const int RecorderInitializationErrorTip = 2131165244;
			
			// aapt resource value: 0x7f070048
			public const int RecorderInitializationErrorTitle = 2131165256;
			
			// aapt resource value: 0x7f07004d
			public const int Recording = 2131165261;
			
			// aapt resource value: 0x7f070050
			public const int RecordingFailed = 2131165264;
			
			// aapt resource value: 0x7f070031
			public const int RecordingFailedTip = 2131165233;
			
			// aapt resource value: 0x7f07003d
			public const int RecordingFailedTitle = 2131165245;
			
			// aapt resource value: 0x7f070051
			public const int RecordingSuccessful = 2131165265;
			
			// aapt resource value: 0x7f07000b
			public const int ResultText = 2131165195;
			
			// aapt resource value: 0x7f07001f
			public const int SelectPicture = 2131165215;
			
			// aapt resource value: 0x7f070025
			public const int SendButtonText = 2131165221;
			
			// aapt resource value: 0x7f07005a
			public const int SendingFailed = 2131165274;
			
			// aapt resource value: 0x7f070034
			public const int SendingFailedTip = 2131165236;
			
			// aapt resource value: 0x7f070040
			public const int SendingFailedTitle = 2131165248;
			
			// aapt resource value: 0x7f07005d
			public const int SendingSuccessful = 2131165277;
			
			// aapt resource value: 0x7f07005e
			public const int ServerCommServiceStopped = 2131165278;
			
			// aapt resource value: 0x7f070015
			public const int SettingsTitle = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int ShowAgainText = 2131165206;
			
			// aapt resource value: 0x7f070018
			public const int Slide1_Text1 = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int Slide1_Text2 = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int Slide3_Text1 = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int Slide3_Text2 = 2131165211;
			
			// aapt resource value: 0x7f07000f
			public const int StartButtonText = 2131165199;
			
			// aapt resource value: 0x7f070049
			public const int StartingAudioRecorderService = 2131165257;
			
			// aapt resource value: 0x7f070057
			public const int StartingServerCommService = 2131165271;
			
			// aapt resource value: 0x7f070065
			public const int StartingStorageService = 2131165285;
			
			// aapt resource value: 0x7f07004f
			public const int StoppedRecording = 2131165263;
			
			// aapt resource value: 0x7f070060
			public const int StorageServiceStopped = 2131165280;
			
			// aapt resource value: 0x7f07005f
			public const int StoreFailed = 2131165279;
			
			// aapt resource value: 0x7f070035
			public const int StoreFailedTip = 2131165237;
			
			// aapt resource value: 0x7f070041
			public const int StoreFailedTitle = 2131165249;
			
			// aapt resource value: 0x7f070066
			public const int StoreSuccessful = 2131165286;
			
			// aapt resource value: 0x7f070021
			public const int TagsDefaultText = 2131165217;
			
			// aapt resource value: 0x7f070027
			public const int TagsHelpText = 2131165223;
			
			// aapt resource value: 0x7f07000c
			public const int TryAgainButtonText = 2131165196;
			
			// aapt resource value: 0x7f07004b
			public const int UpdatePrepareCounter = 2131165259;
			
			// aapt resource value: 0x7f07004e
			public const int UpdateRecordingCounter = 2131165262;
			
			// aapt resource value: 0x7f07002e
			public const int VersionHeading = 2131165230;
			
			// aapt resource value: 0x7f07005b
			public const int WaitingForResponse = 2131165275;
			
			// aapt resource value: 0x7f070061
			public const int WriteFailed = 2131165281;
			
			// aapt resource value: 0x7f070036
			public const int WriteFailedTip = 2131165238;
			
			// aapt resource value: 0x7f070042
			public const int WriteFailedTitle = 2131165250;
			
			// aapt resource value: 0x7f070064
			public const int WriteSuccessful = 2131165284;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090002
			public const int SkillStore_Theme_Application_Splash = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int SkillStore_Theme_Help_SlideShow = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int SkillStore_Theme_Main_TabbedActivity = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int Preferences = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
